# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 908b00951d6f1f6c3bbf3fd7068524dd00cf6a77a72c1afc411e5d3d253753012eecb752fb5f8068ab07b34ae80fd7538b228009f5f5dc59e0c3580647d2103e

test:
  secret_key_base: a35664a824a16e460bffcead948aba030d5296453de98922535ef4dc38ad20b3a39ec253bd1fe8e7e333167b62ba4a9705401ba2c356abc942aeb6ee06e4926d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
